### ISSUE TITLE
breaks google sheets (i think)

### ISSUE THREAD

**Issue by brandonmp** [jsconsole/chrome-jsconsole#4]
Having the extension enabled when loading google sheets causes this error alert:

![image](https://user-images.githubusercontent.com/14139991/29644420-dddd8302-8843-11e7-8ef1-0e595c318657.png)

Disabling JSConsole makes sheets load like normal. when JSConsole is enabled, console throws this error when opening a google sheet: 

```
Uncaught D9a {message: "Error in protected function: js is not a function", $n: TypeError: js is not a function
    at FD (https://docs.google.com/static/spreadsheets2/client/js/10…, stack: "TypeError: js is not a function↵    at FD (https:/…t/js/1043487106-ritz_waffle_i18n_core.js:2182:94)"}$n: TypeError: js is not a function
    at FD (https://docs.google.com/static/spreadsheets2/client/js/1043487106-ritz_waffle_i18n_core.js:1679:785)
    at uWa.jWa [as constructor] (https://docs.google.com/static/spreadsheets2/client/js/1043487106-ritz_waffle_i18n_core.js:1679:547)
    at new uWa (https://docs.google.com/static/spreadsheets2/client/js/1043487106-ritz_waffle_i18n_core.js:1685:296)
    at new xWa (https://docs.google.com/static/spreadsheets2/client/js/1043487106-ritz_waffle_i18n_core.js:1685:648)
    at oXa (https://docs.google.com/static/spreadsheets2/client/js/1043487106-ritz_waffle_i18n_core.js:1722:311)
    at wXa (https://docs.google.com/static/spreadsheets2/client/js/1043487106-ritz_waffle_i18n_core.js:1722:43)
    at vXa (https://docs.google.com/static/spreadsheets2/client/js/1043487106-ritz_waffle_i18n_core.js:1721:262)
    at sE.exec (https://docs.google.com/static/spreadsheets2/client/js/1043487106-ritz_waffle_i18n_core.js:1722:737)
    at REb.c (https://docs.google.com/static/spreadsheets2/client/js/1043487106-ritz_waffle_i18n_core.js:3461:617)
    at Array.forEach (<anonymous>)
    at x (https://docs.google.com/static/spreadsheets2/client/js/1043487106-ritz_waffle_i18n_core.js:49:120)
    at TG.<anonymous> (https://docs.google.com/static/spreadsheets2/client/js/1043487106-ritz_waffle_i18n_core.js:3461:644)
    at yB (https://docs.google.com/static/spreadsheets2/client/js/1043487106-ritz_waffle_i18n_core.js:1335:135)
    at SEb (https://docs.google.com/static/spreadsheets2/client/js/1043487106-ritz_waffle_i18n_core.js:3461:624)
    at DXb.p.MOb (https://docs.google.com/static/spreadsheets2/client/js/1043487106-ritz_waffle_i18n_core.js:4214:90)
    at Dm (https://docs.google.com/static/spreadsheets2/client/js/1043487106-ritz_waffle_i18n_core.js:480:413)
    at DXb.p.fjb (https://docs.google.com/static/spreadsheets2/client/js/1043487106-ritz_waffle_i18n_core.js:4209:313)
    at Dm (https://docs.google.com/static/spreadsheets2/client/js/1043487106-ritz_waffle_i18n_core.js:480:413)
    at hUb (https://docs.google.com/static/spreadsheets2/client/js/1043487106-ritz_waffle_i18n_core.js:4076:365)
    at fUb.p.$La (https://docs.google.com/static/spreadsheets2/client/js/1043487106-ritz_waffle_i18n_core.js:4073:130)
    at fUb.p.lya (https://docs.google.com/static/spreadsheets2/client/js/1043487106-ritz_waffle_i18n_core.js:4072:247)
    at fUb.p.HEb (https://docs.google.com/static/spreadsheets2/client/js/1043487106-ritz_waffle_i18n_core.js:4072:189)
    at c (https://docs.google.com/static/spreadsheets2/client/js/1043487106-ritz_waffle_i18n_core.js:2182:94)message: "js is not a function"stack: "TypeError: js is not a function↵    at FD (https://docs.google.com/static/spreadsheets2/client/js/1043487106-ritz_waffle_i18n_core.js:1679:785)↵    at uWa.jWa [as constructor] (https://docs.google.com/static/spreadsheets2/client/js/1043487106-ritz_waffle_i18n_core.js:1679:547)↵    at new uWa (https://docs.google.com/static/spreadsheets2/client/js/1043487106-ritz_waffle_i18n_core.js:1685:296)↵    at new xWa (https://docs.google.com/static/spreadsheets2/client/js/1043487106-ritz_waffle_i18n_core.js:1685:648)↵    at oXa (https://docs.google.com/static/spreadsheets2/client/js/1043487106-ritz_waffle_i18n_core.js:1722:311)↵    at wXa (https://docs.google.com/static/spreadsheets2/client/js/1043487106-ritz_waffle_i18n_core.js:1722:43)↵    at vXa (https://docs.google.com/static/spreadsheets2/client/js/1043487106-ritz_waffle_i18n_core.js:1721:262)↵    at sE.exec (https://docs.google.com/static/spreadsheets2/client/js/1043487106-ritz_waffle_i18n_core.js:1722:737)↵    at REb.c (https://docs.google.com/static/spreadsheets2/client/js/1043487106-ritz_waffle_i18n_core.js:3461:617)↵    at Array.forEach (<anonymous>)↵    at x (https://docs.google.com/static/spreadsheets2/client/js/1043487106-ritz_waffle_i18n_core.js:49:120)↵    at TG.<anonymous> (https://docs.google.com/static/spreadsheets2/client/js/1043487106-ritz_waffle_i18n_core.js:3461:644)↵    at yB (https://docs.google.com/static/spreadsheets2/client/js/1043487106-ritz_waffle_i18n_core.js:1335:135)↵    at SEb (https://docs.google.com/static/spreadsheets2/client/js/1043487106-ritz_waffle_i18n_core.js:3461:624)↵    at DXb.p.MOb (https://docs.google.com/static/spreadsheets2/client/js/1043487106-ritz_waffle_i18n_core.js:4214:90)↵    at Dm (https://docs.google.com/static/spreadsheets2/client/js/1043487106-ritz_waffle_i18n_core.js:480:413)↵    at DXb.p.fjb (https://docs.google.com/static/spreadsheets2/client/js/1043487106-ritz_waffle_i18n_core.js:4209:313)↵    at Dm (https://docs.google.com/static/spreadsheets2/client/js/1043487106-ritz_waffle_i18n_core.js:480:413)↵    at hUb (https://docs.google.com/static/spreadsheets2/client/js/1043487106-ritz_waffle_i18n_core.js:4076:365)↵    at fUb.p.$La (https://docs.google.com/static/spreadsheets2/client/js/1043487106-ritz_waffle_i18n_core.js:4073:130)↵    at fUb.p.lya (https://docs.google.com/static/spreadsheets2/client/js/1043487106-ritz_waffle_i18n_core.js:4072:247)↵    at fUb.p.HEb (https://docs.google.com/static/spreadsheets2/client/js/1043487106-ritz_waffle_i18n_core.js:4072:189)↵    at c (https://docs.google.com/static/spreadsheets2/client/js/1043487106-ritz_waffle_i18n_core.js:2182:94)"__proto__: Errormessage: "Error in protected function: js is not a function"stack: "TypeError: js is not a function↵    at FD (https://docs.google.com/static/spreadsheets2/client/js/1043487106-ritz_waffle_i18n_core.js:1679:785)↵    at uWa.jWa [as constructor] (https://docs.google.com/static/spreadsheets2/client/js/1043487106-ritz_waffle_i18n_core.js:1679:547)↵    at new uWa (https://docs.google.com/static/spreadsheets2/client/js/1043487106-ritz_waffle_i18n_core.js:1685:296)↵    at new xWa (https://docs.google.com/static/spreadsheets2/client/js/1043487106-ritz_waffle_i18n_core.js:1685:648)↵    at oXa (https://docs.google.com/static/spreadsheets2/client/js/1043487106-ritz_waffle_i18n_core.js:1722:311)↵    at wXa (https://docs.google.com/static/spreadsheets2/client/js/1043487106-ritz_waffle_i18n_core.js:1722:43)↵    at vXa (https://docs.google.com/static/spreadsheets2/client/js/1043487106-ritz_waffle_i18n_core.js:1721:262)↵    at sE.exec (https://docs.google.com/static/spreadsheets2/client/js/1043487106-ritz_waffle_i18n_core.js:1722:737)↵    at REb.c (https://docs.google.com/static/spreadsheets2/client/js/1043487106-ritz_waffle_i18n_core.js:3461:617)↵    at Array.forEach (<anonymous>)↵    at x (https://docs.google.com/static/spreadsheets2/client/js/1043487106-ritz_waffle_i18n_core.js:49:120)↵    at TG.<anonymous> (https://docs.google.com/static/spreadsheets2/client/js/1043487106-ritz_waffle_i18n_core.js:3461:644)↵    at yB (https://docs.google.com/static/spreadsheets2/client/js/1043487106-ritz_waffle_i18n_core.js:1335:135)↵    at SEb (https://docs.google.com/static/spreadsheets2/client/js/1043487106-ritz_waffle_i18n_core.js:3461:624)↵    at DXb.p.MOb (https://docs.google.com/static/spreadsheets2/client/js/1043487106-ritz_waffle_i18n_core.js:4214:90)↵    at Dm (https://docs.google.com/static/spreadsheets2/client/js/1043487106-ritz_waffle_i18n_core.js:480:413)↵    at DXb.p.fjb (https://docs.google.com/static/spreadsheets2/client/js/1043487106-ritz_waffle_i18n_core.js:4209:313)↵    at Dm (https://docs.google.com/static/spreadsheets2/client/js/1043487106-ritz_waffle_i18n_core.js:480:413)↵    at hUb (https://docs.google.com/static/spreadsheets2/client/js/1043487106-ritz_waffle_i18n_core.js:4076:365)↵    at fUb.p.$La (https://docs.google.com/static/spreadsheets2/client/js/1043487106-ritz_waffle_i18n_core.js:4073:130)↵    at fUb.p.lya (https://docs.google.com/static/spreadsheets2/client/js/1043487106-ritz_waffle_i18n_core.js:4072:247)↵    at fUb.p.HEb (https://docs.google.com/static/spreadsheets2/client/js/1043487106-ritz_waffle_i18n_core.js:4072:189)↵    at c (https://docs.google.com/static/spreadsheets2/client/js/1043487106-ritz_waffle_i18n_core.js:2182:94)"__proto__: Ma
c @ 1043487106-ritz_waffle_i18n_core.js:2182
```

**Comment by rachitGulati** [comment]
Yes, they are conflicting.I have pushed the version 0.0.6 for the fix. Thanks for the feedback.

You can update it via Settings > MoreTools > Extensions > (Mark Tick) Developer Mode > Update Extensions.
